version: "3.2"
services:
  app:
    user: developer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: ${HOME}${USERPROFILE}/.ssh
        target: /root/.ssh
    working_dir: /workspace
    command: sleep infinity
    environment:
      BUNDLE_PATH: verdor/bundle
      INTERFACE: "0.0.0.0"
      PATH: /workspace/bin.
    ports:
      - "3000:3000"