version: "3.2"
services:
  menu:
    user: developer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: ${HOME}${USERPROFILE}/.ssh
        target: /home/developer/.ssh
    working_dir: /workspace
    command: sleep infinity
    environment:
      BUNDLE_PATH: vendor/bundle
      INTERFACE: "0.0.0.0"
    ports:
      - "6000:6000"